CREATE TABLE IF NOT EXISTS EMPLOYEES (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  USER_ID INTEGER NOT NULL UNIQUE,
  EMPLOYEE_CODE VARCHAR(40) NOT NULL UNIQUE,
  PHONE VARCHAR(40),
  DEPARTMENT_ID INTEGER,
  DESIGNATION VARCHAR(120),
  JOINING_DATE DATE,
  MANAGER_ID INTEGER,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  ADDRESS VARCHAR(1000),
  DATE_OF_BIRTH DATE,
  GENDER VARCHAR(40),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE EMPLOYEES ADD COLUMN IF NOT EXISTS ADDRESS VARCHAR(1000);
ALTER TABLE EMPLOYEES ADD COLUMN IF NOT EXISTS DATE_OF_BIRTH DATE;
ALTER TABLE EMPLOYEES ADD COLUMN IF NOT EXISTS GENDER VARCHAR(40);

CREATE TABLE IF NOT EXISTS LEAVE_TYPES (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  NAME VARCHAR(40) NOT NULL UNIQUE,
  CODE VARCHAR(40),
  DESCRIPTION VARCHAR(500),
  DEFAULT_DAYS NUMBER(5,1) NOT NULL DEFAULT 0,
  IS_PAID BOOLEAN DEFAULT TRUE,
  YEARLY_QUOTA NUMBER(5,1),
  REQUIRES_DOCUMENT BOOLEAN DEFAULT FALSE,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE LEAVE_TYPES ADD COLUMN IF NOT EXISTS CODE VARCHAR(40);
ALTER TABLE LEAVE_TYPES ADD COLUMN IF NOT EXISTS IS_PAID BOOLEAN;
ALTER TABLE LEAVE_TYPES ADD COLUMN IF NOT EXISTS YEARLY_QUOTA NUMBER(5,1);
ALTER TABLE LEAVE_TYPES ADD COLUMN IF NOT EXISTS REQUIRES_DOCUMENT BOOLEAN;
ALTER TABLE LEAVE_TYPES ADD COLUMN IF NOT EXISTS IS_ACTIVE BOOLEAN;
ALTER TABLE LEAVE_TYPES ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;

INSERT INTO LEAVE_TYPES (NAME, CODE, DESCRIPTION, DEFAULT_DAYS, IS_PAID, YEARLY_QUOTA, REQUIRES_DOCUMENT, IS_ACTIVE)
SELECT 'CASUAL', 'CL', 'Personal leave', 10, TRUE, 10, FALSE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM LEAVE_TYPES WHERE UPPER(NAME) = 'CASUAL' OR UPPER(CODE) = 'CL');

INSERT INTO LEAVE_TYPES (NAME, CODE, DESCRIPTION, DEFAULT_DAYS, IS_PAID, YEARLY_QUOTA, REQUIRES_DOCUMENT, IS_ACTIVE)
SELECT 'SICK', 'SL', 'Medical leave', 10, TRUE, 10, FALSE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM LEAVE_TYPES WHERE UPPER(NAME) = 'SICK' OR UPPER(CODE) = 'SL');

INSERT INTO LEAVE_TYPES (NAME, CODE, DESCRIPTION, DEFAULT_DAYS, IS_PAID, YEARLY_QUOTA, REQUIRES_DOCUMENT, IS_ACTIVE)
SELECT 'ANNUAL', 'AL', 'Annual leave', 20, TRUE, 20, FALSE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM LEAVE_TYPES WHERE UPPER(NAME) = 'ANNUAL' OR UPPER(CODE) = 'AL');

UPDATE LEAVE_TYPES
SET CODE = CASE UPPER(NAME)
  WHEN 'CASUAL' THEN 'CL'
  WHEN 'SICK' THEN 'SL'
  WHEN 'ANNUAL' THEN 'AL'
  ELSE UPPER(REPLACE(TRIM(NAME), ' ', '_'))
END
WHERE CODE IS NULL OR TRIM(CODE) = '';

UPDATE LEAVE_TYPES
SET YEARLY_QUOTA = IFF(DEFAULT_DAYS > 0, DEFAULT_DAYS, NULL)
WHERE YEARLY_QUOTA IS NULL AND DEFAULT_DAYS IS NOT NULL;

UPDATE LEAVE_TYPES SET IS_PAID = TRUE WHERE IS_PAID IS NULL;
UPDATE LEAVE_TYPES SET IS_PAID = FALSE WHERE UPPER(CODE) = 'LWP' OR UPPER(NAME) IN ('LEAVE WITHOUT PAY', 'UNPAID LEAVE');
UPDATE LEAVE_TYPES SET REQUIRES_DOCUMENT = FALSE WHERE REQUIRES_DOCUMENT IS NULL;
UPDATE LEAVE_TYPES SET IS_ACTIVE = TRUE WHERE IS_ACTIVE IS NULL;
UPDATE LEAVE_TYPES SET CREATED_AT = CURRENT_TIMESTAMP() WHERE CREATED_AT IS NULL;
UPDATE LEAVE_TYPES SET UPDATED_AT = CURRENT_TIMESTAMP() WHERE UPDATED_AT IS NULL;

CREATE TABLE IF NOT EXISTS LEAVE_REQUESTS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  EMPLOYEE_ID INTEGER NOT NULL,
  LEAVE_TYPE_ID INTEGER NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  TOTAL_DAYS NUMBER(6,1) NOT NULL,
  DAYS_COUNT NUMBER(6,1),
  HALF_DAY_SESSION VARCHAR(20),
  DOCUMENT_URL VARCHAR(500),
  REASON VARCHAR(2000) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  APPROVED_BY INTEGER,
  APPROVED_AT TIMESTAMP_NTZ,
  DECIDED_AT TIMESTAMP_NTZ,
  DECISION_NOTE VARCHAR(1000),
  AUTO_APPROVED BOOLEAN DEFAULT FALSE,
  REJECTION_REASON VARCHAR(1000),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS EMPLOYEE_ID INTEGER;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS LEAVE_TYPE_ID INTEGER;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS START_DATE DATE;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS END_DATE DATE;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS TOTAL_DAYS NUMBER(6,1);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS DAYS_COUNT NUMBER(6,1);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS HALF_DAY_SESSION VARCHAR(20);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS DOCUMENT_URL VARCHAR(500);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS REASON VARCHAR(2000);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS APPROVED_BY INTEGER;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS APPROVED_AT TIMESTAMP_NTZ;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS DECIDED_AT TIMESTAMP_NTZ;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS DECISION_NOTE VARCHAR(1000);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS AUTO_APPROVED BOOLEAN;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS REJECTION_REASON VARCHAR(1000);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;
ALTER TABLE LEAVE_REQUESTS ALTER COLUMN APPROVED_BY DROP NOT NULL;

UPDATE LEAVE_REQUESTS SET DAYS_COUNT = TOTAL_DAYS WHERE DAYS_COUNT IS NULL AND TOTAL_DAYS IS NOT NULL;
UPDATE LEAVE_REQUESTS SET DECIDED_AT = APPROVED_AT WHERE DECIDED_AT IS NULL AND APPROVED_AT IS NOT NULL;
UPDATE LEAVE_REQUESTS SET DECISION_NOTE = REJECTION_REASON WHERE DECISION_NOTE IS NULL AND REJECTION_REASON IS NOT NULL;
UPDATE LEAVE_REQUESTS SET AUTO_APPROVED = FALSE WHERE AUTO_APPROVED IS NULL;
UPDATE LEAVE_REQUESTS SET CREATED_AT = CURRENT_TIMESTAMP() WHERE CREATED_AT IS NULL;
UPDATE LEAVE_REQUESTS SET UPDATED_AT = CURRENT_TIMESTAMP() WHERE UPDATED_AT IS NULL;

CREATE TABLE IF NOT EXISTS LEAVE_BALANCES (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  EMPLOYEE_ID INTEGER NOT NULL,
  LEAVE_TYPE_ID INTEGER NOT NULL,
  YEAR INTEGER NOT NULL,
  TOTAL NUMBER(8,1) NOT NULL DEFAULT 0,
  USED NUMBER(8,1) NOT NULL DEFAULT 0,
  PENDING NUMBER(8,1) NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS EMPLOYEE_ID INTEGER;
ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS LEAVE_TYPE_ID INTEGER;
ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS YEAR INTEGER;
ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS TOTAL NUMBER(8,1);
ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS USED NUMBER(8,1);
ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS PENDING NUMBER(8,1);
ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE LEAVE_BALANCES ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;

UPDATE LEAVE_BALANCES SET TOTAL = 9999 WHERE TOTAL IS NULL;
UPDATE LEAVE_BALANCES SET USED = 0 WHERE USED IS NULL;
UPDATE LEAVE_BALANCES SET PENDING = 0 WHERE PENDING IS NULL;
UPDATE LEAVE_BALANCES SET CREATED_AT = CURRENT_TIMESTAMP() WHERE CREATED_AT IS NULL;
UPDATE LEAVE_BALANCES SET UPDATED_AT = CURRENT_TIMESTAMP() WHERE UPDATED_AT IS NULL;

INSERT INTO LEAVE_BALANCES (EMPLOYEE_ID, LEAVE_TYPE_ID, YEAR, TOTAL, USED, PENDING, CREATED_AT, UPDATED_AT)
SELECT E.ID,
       T.ID,
       YEAR(CURRENT_DATE()),
       COALESCE(T.YEARLY_QUOTA, 9999),
       COALESCE(R.USED_DAYS, 0),
       COALESCE(R.PENDING_DAYS, 0),
       CURRENT_TIMESTAMP(),
       CURRENT_TIMESTAMP()
FROM EMPLOYEES E
CROSS JOIN LEAVE_TYPES T
LEFT JOIN (
  SELECT EMPLOYEE_ID,
         LEAVE_TYPE_ID,
         SUM(IFF(STATUS = 'APPROVED', COALESCE(DAYS_COUNT, TOTAL_DAYS), 0)) AS USED_DAYS,
         SUM(IFF(STATUS = 'PENDING', COALESCE(DAYS_COUNT, TOTAL_DAYS), 0)) AS PENDING_DAYS
  FROM LEAVE_REQUESTS
  WHERE YEAR(START_DATE) = YEAR(CURRENT_DATE())
  GROUP BY EMPLOYEE_ID, LEAVE_TYPE_ID
) R ON R.EMPLOYEE_ID = E.ID AND R.LEAVE_TYPE_ID = T.ID
WHERE T.IS_ACTIVE = TRUE
  AND NOT EXISTS (
    SELECT 1 FROM LEAVE_BALANCES B
    WHERE B.EMPLOYEE_ID = E.ID
      AND B.LEAVE_TYPE_ID = T.ID
      AND B.YEAR = YEAR(CURRENT_DATE())
  );

CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  USER_ID INTEGER NOT NULL,
  TYPE VARCHAR(60) NOT NULL,
  TITLE VARCHAR(200) NOT NULL,
  MESSAGE VARCHAR(2000) NOT NULL,
  LINK VARCHAR(500),
  RELATED_ID INTEGER,
  IS_READ BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  READ_AT TIMESTAMP_NTZ
);

ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS USER_ID INTEGER;
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS TYPE VARCHAR(60);
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS TITLE VARCHAR(200);
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS MESSAGE VARCHAR(2000);
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS LINK VARCHAR(500);
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS RELATED_ID INTEGER;
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS IS_READ BOOLEAN;
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_NTZ;
ALTER TABLE NOTIFICATIONS ADD COLUMN IF NOT EXISTS READ_AT TIMESTAMP_NTZ;

UPDATE NOTIFICATIONS SET IS_READ = FALSE WHERE IS_READ IS NULL;
UPDATE NOTIFICATIONS SET CREATED_AT = CURRENT_TIMESTAMP() WHERE CREATED_AT IS NULL;