-- Migration: 002_agent_audit_log.sql
-- Create audit log table for AI Agent tool calls and executions

CREATE TABLE IF NOT EXISTS AGENT_AUDIT_LOG (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  REQUEST_ID VARCHAR(100),
  USER_ID INTEGER NOT NULL,
  TOOL_NAME VARCHAR(100) NOT NULL,
  ARGUMENTS VARCHAR(4000),
  STATUS VARCHAR(50) NOT NULL,
  ERROR_MESSAGE VARCHAR(1000),
  EXECUTION_TIME_MS INTEGER,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
