-- Snowflake Idempotent Migration: Employee Soft Termination & Audit Table

-- 1. Add termination columns to USERS table
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS TERMINATED_AT TIMESTAMP_NTZ;
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS TERMINATED_BY INTEGER;
ALTER TABLE USERS ADD COLUMN IF NOT EXISTS TERMINATION_REASON VARCHAR(2000);

-- 2. Add termination columns to EMPLOYEES table
ALTER TABLE EMPLOYEES ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE EMPLOYEES ADD COLUMN IF NOT EXISTS TERMINATED_AT TIMESTAMP_NTZ;
ALTER TABLE EMPLOYEES ADD COLUMN IF NOT EXISTS TERMINATED_BY INTEGER;
ALTER TABLE EMPLOYEES ADD COLUMN IF NOT EXISTS TERMINATION_REASON VARCHAR(2000);

-- 3. Backfill existing records to ACTIVE
UPDATE USERS SET STATUS = 'ACTIVE' WHERE STATUS IS NULL;
UPDATE EMPLOYEES SET STATUS = 'ACTIVE' WHERE STATUS IS NULL;

-- 4. Create USER_STATUS_LOGS audit table
CREATE TABLE IF NOT EXISTS USER_STATUS_LOGS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  USER_ID INTEGER NOT NULL,
  ACTION VARCHAR(20) NOT NULL, -- 'TERMINATED', 'REACTIVATED'
  PERFORMED_BY INTEGER NOT NULL,
  REASON VARCHAR(2000),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
