-- USERS is an existing table and is intentionally not recreated here.
CREATE TABLE IF NOT EXISTS DEPARTMENTS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  NAME VARCHAR(120) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(1000),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  USER_ID INTEGER NOT NULL UNIQUE,
  EMPLOYEE_CODE VARCHAR(40) NOT NULL UNIQUE,
  PHONE VARCHAR(40),
  DEPARTMENT_ID INTEGER,
  DESIGNATION VARCHAR(120),
  JOINING_DATE DATE,
  MANAGER_ID INTEGER,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ATTENDANCE (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  EMPLOYEE_ID INTEGER NOT NULL,
  ATTENDANCE_DATE DATE NOT NULL,
  CHECK_IN TIMESTAMP_NTZ,
  CHECK_OUT TIMESTAMP_NTZ,
  STATUS VARCHAR(20) NOT NULL,
  WORKING_HOURS NUMBER(8,2),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT UQ_ATTENDANCE_EMPLOYEE_DATE UNIQUE (EMPLOYEE_ID, ATTENDANCE_DATE)
);

CREATE TABLE IF NOT EXISTS LEAVE_TYPES (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  NAME VARCHAR(40) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR(500),
  DEFAULT_DAYS NUMBER(5,1) NOT NULL DEFAULT 0,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS LEAVE_REQUESTS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  EMPLOYEE_ID INTEGER NOT NULL,
  LEAVE_TYPE_ID INTEGER NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  TOTAL_DAYS NUMBER(6,1) NOT NULL,
  REASON VARCHAR(2000) NOT NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  APPROVED_BY INTEGER,
  APPROVED_AT TIMESTAMP_NTZ,
  REJECTION_REASON VARCHAR(1000),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS TASKS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  TITLE VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(4000),
  ASSIGNED_TO INTEGER NOT NULL,
  ASSIGNED_BY INTEGER NOT NULL,
  PRIORITY VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
  STATUS VARCHAR(20) NOT NULL DEFAULT 'TODO',
  DUE_DATE DATE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  COMPLETED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS AI_CONVERSATIONS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  USER_ID INTEGER NOT NULL,
  TITLE VARCHAR(120) NOT NULL DEFAULT 'New conversation',
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS AI_MESSAGES (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  CONVERSATION_ID INTEGER NOT NULL,
  ROLE VARCHAR(10) NOT NULL,
  CONTENT VARCHAR(8000) NOT NULL,
  MODEL VARCHAR(80),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PASSWORD_RESET_TOKENS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  USER_ID INTEGER NOT NULL,
  TOKEN_HASH VARCHAR(128) NOT NULL,
  EXPIRES_AT TIMESTAMP_NTZ NOT NULL,
  USED BOOLEAN DEFAULT FALSE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Snowflake standard-table UNIQUE constraints are informational, so services also check duplicates.