INSERT INTO LEAVE_TYPES (NAME, DESCRIPTION, DEFAULT_DAYS)
SELECT 'CASUAL', 'Personal leave', 10
WHERE NOT EXISTS (SELECT 1 FROM LEAVE_TYPES WHERE NAME = 'CASUAL');

INSERT INTO LEAVE_TYPES (NAME, DESCRIPTION, DEFAULT_DAYS)
SELECT 'SICK', 'Medical leave', 10
WHERE NOT EXISTS (SELECT 1 FROM LEAVE_TYPES WHERE NAME = 'SICK');

INSERT INTO LEAVE_TYPES (NAME, DESCRIPTION, DEFAULT_DAYS)
SELECT 'ANNUAL', 'Annual leave', 20
WHERE NOT EXISTS (SELECT 1 FROM LEAVE_TYPES WHERE NAME = 'ANNUAL');

-- After review, migrate legacy user accounts to the new employee role:
-- UPDATE USERS SET ROLE = 'EMPLOYEE', UPDATED_AT = CURRENT_TIMESTAMP() WHERE ROLE = 'USER';