-- Add nullable decision metadata without changing existing leave records.
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS DECIDED_AT TIMESTAMP_NTZ;
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS DECISION_NOTE VARCHAR(1000);
ALTER TABLE LEAVE_REQUESTS ADD COLUMN IF NOT EXISTS AUTO_APPROVED BOOLEAN;

-- APPROVED_BY exists on older schemas and must remain nullable for automatic decisions.
ALTER TABLE LEAVE_REQUESTS ALTER COLUMN APPROVED_BY DROP NOT NULL;