-- Migration 005: Live Chat Schema
-- Tables for real-time live chat between employees, managers, HR, and admins.

CREATE TABLE IF NOT EXISTS CHAT_CONVERSATIONS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  USER_A_ID INTEGER NOT NULL,
  USER_B_ID INTEGER NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_MESSAGE_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT UQ_CHAT_CONVERSATION_PAIR UNIQUE (USER_A_ID, USER_B_ID)
);

CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  CONVERSATION_ID INTEGER NOT NULL,
  SENDER_ID INTEGER NOT NULL,
  BODY VARCHAR(4000) NOT NULL,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  DELIVERED_AT TIMESTAMP_NTZ,
  READ_AT TIMESTAMP_NTZ,
  CLIENT_MESSAGE_ID VARCHAR(128),
  IS_DELETED BOOLEAN DEFAULT FALSE
);

-- Note: In Snowflake standard tables, UNIQUE constraints are informative.
-- Backend ensures normalized pairs: USER_A_ID = LEAST(user1, user2), USER_B_ID = GREATEST(user1, user2).
