-- Migration 007: Holidays Schema
-- Centralized organization & public holidays table.
-- One row per holiday; accessible to all active employees.

CREATE TABLE IF NOT EXISTS HOLIDAYS (
  ID INTEGER AUTOINCREMENT START 1 INCREMENT 1,
  NAME VARCHAR(150) NOT NULL,
  DESCRIPTION VARCHAR(1000),
  HOLIDAY_DATE DATE NOT NULL,
  END_DATE DATE,
  TYPE VARCHAR(30) NOT NULL DEFAULT 'PUBLIC',
  COLOR VARCHAR(20),
  IS_RECURRING BOOLEAN NOT NULL DEFAULT FALSE,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  CREATED_BY INTEGER,
  UPDATED_BY INTEGER,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT UQ_HOLIDAY_DATE_NAME UNIQUE (HOLIDAY_DATE, NAME)
);

-- Note: Snowflake standard-table UNIQUE constraints are informational,
-- so backend application logic also enforces uniqueness on (NAME, HOLIDAY_DATE, STATUS).
